<?xml version="1.0"?>
<!DOCTYPE question-paper[
<!ELEMENT question-paper (question*)>
<!ELEMENT question (text, optionA, optionB, optionC, optionD, answer)>
<!ELEMENT text (#PCDATA)>

<!ELEMENT optionA (#PCDATA)>
<!ELEMENT optionB (#PCDATA)>
<!ELEMENT optionC (#PCDATA)>
<!ELEMENT optionD (#PCDATA)>
<!ELEMENT answer (#PCDATA)>
<!ATTLIST question no CDATA #REQUIRED>
<!ATTLIST answer value (optionA|optionB|optionC|optionD) #REQUIRED>
]>
<question-paper>
    <question no="1">
        <text>Q1:</text>
        <optionA>1A</optionA>
        <optionB>1B</optionB>
        <optionC>1C</optionC>
        <optionD>1D</optionD>
        <answer value="optionC">37</answer>
    </question>
    <question no="2">
        <text>Q2</text>
        <optionA>2A</optionA>
        <optionB>2B</optionB>
        <optionC>2C</optionC>
        <optionD>2D</optionD>
        <answer value="optionC">0.6976</answer>
    </question>
</question-paper>